FROM node:21

WORKDIR /app

COPY ./package.json ./package-lock.json ./

ARG BW_PASSWORD
ENV BW_PASSWORD=${BW_PASSWORD}

ARG MONGODB_URI
ENV MONGODB_URI=${MONGODB_URI}

# "Disable" Husky
RUN npm pkg delete scripts.prepare
RUN npm config set fetch-retry-maxtimeout 600000 -g

RUN npm cache clean --force
RUN npm ci

COPY ./ ./

EXPOSE 3000

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

RUN ./entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["npm", "run", "docker-run"]