services:
  app:
    container_name: jennifer-anns-app
    build:
      dockerfile: ./Dockerfile.dev
      args:
        BW_PASSWORD: ${BW_PASSWORD}
        MONGODB_URI: mongodb://mongo:27017/jennifer-anns
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/jennifer-anns
      BW_PASSWORD: ${BW_PASSWORD}
    networks:
      - jennifer-anns-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - jennifer-anns-net
    volumes:
      - mongodb-data:/data/db

networks:
  jennifer-anns-net:
    driver: bridge

volumes:
  mongodb-data: