services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/jennifer-anns
    env_file:
      - bitwarden.env
    networks:
      - jennifer-anns-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - jennifer-anns-net

networks:
  jennifer-anns-net:
    driver: bridge
