FROM node:21 AS deps
WORKDIR /app

COPY package*.json ./
COPY entrypoint.sh ./
RUN npm cache clean --force
RUN npm install

FROM node:21 as dev

WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN ls -la /app/node_modules
CMD ["npm", "run", "dev"]