name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tailwind CSS Build
        run: npx tailwindcss build -o styles.css

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint .

      - name: Run Type Checking
        run: npx tsc --noEmit
