name: Reusable Workflow for Updating Game Popularity for Specific Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  run-game-popularity-updater:
    name: Update Game Popularity for ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: API Request to Update Game Popularity Endpoint
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          CRON_KEY: ${{ secrets.GAME_POPULARITY_CRON_KEY }}
          URL: ${{ secrets.DEPLOYMENT_BASE_URL }}
        run: |
          echo "Updating game popularity"
          echo "x-api-key: $CRON_KEY"
          echo "$URL/api/games/popularity"
          # Add -v flag for verbose output and --fail flag to fail on HTTP errors
          RESPONSE=$(curl -v --fail -X POST \
            -H "x-api-key: $CRON_KEY" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d "{}" \
            "$URL/api/games/popularity" 2>&1)
          
          # Capture the exit status of curl
          CURL_EXIT_CODE=$?
          
          echo "Full Response: $RESPONSE"
          
          if [[ $CURL_EXIT_CODE -eq 0 ]]; then
            echo "Game popularities updated successfully."
          else
            echo "Failed to update game popularities. Curl exit code: $CURL_EXIT_CODE"
            echo "Error details: $RESPONSE"
            exit 1
          fi
